- Type: 1
  Level: 4
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
- Type: 2
  Level: 8
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
- Type: 3
  Level: 7
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
- Type: 4
  Level: 3
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
- Type: 5
  Level: 6
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
- Type: 6
  Level: 1
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
- Type: 7
  Level: 3
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
- Type: 8
  Level: 5
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
- Type: 9
  Level: 9
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
- Type: 10
  Level: 1
  Status: 0
  Difficulty: 0
  MapId: 0
  Value: 0
