ShapeRefitLefend:
  - KartID: 24410
    ShapeSuitID: 130792
    KarNameLen: 爆天雷诺-千里
  - KartID: 24410
    ShapeSuitID: 130793
    KarNameLen: 爆天雷诺-澄明
  - KartID: 24410
    ShapeSuitID: 130794
    KarNameLen: 爆天雷诺-阳焱
  - KartID: 24410
    ShapeSuitID: 130795
    KarNameLen: 爆天雷诺-碧渊
  - KartID: 24410
    ShapeSuitID: 130796
    KarNameLen: 爆天雷诺-玄隐
  - KartID: 24410
    ShapeSuitID: 130797
    KarNameLen: 爆天雷诺-紫夜
  - KartID: 24410
    ShapeSuitID: 131937
    KarNameLen: 爆天雷诺-金刚
  - KartID: 24410
    ShapeSuitID: 130791
    KarNameLen: 爆天雷诺-鸿钧
  - KartID: 24410
    ShapeSuitID: 129288
    KarNameLen: 风之使者-兰
  - KartID: 91957
    ShapeSuitID: 124680
    KarNameLen: 银天使-蓐收
  - KartID: 109563
    ShapeSuitID: 110710
    GradeResourceLen: niunianxianding
    KarNameLen: 至尊-冰凤
  - KartID: 119067
    ShapeSuitID: 130777
    KarNameLen: 特洛伊-冰霜骑士
  - KartID: 106675
    ShapeSuitID: 130778
    KarNameLen: 终极众神-吕布
  - KartID: 126345
    ShapeSuitID: 129286
    KarNameLen: 源极-帝皇侠
  - KartID: 129099
    ShapeSuitID: 127616
    GradeResourceLen: tunianxianding
    KarNameLen: 至尊-玉麒麟
  - KartID: 77236
    ShapeSuitID: 127618
    KarNameLen: 至尊-影龙
  - KartID: 77236
    ShapeSuitID: 127617
    KarNameLen: 至曜-岩武
  - KartID: 130538
    ShapeSuitID: 130539
    KarNameLen: 奥莉娜・天穹战音
  - KartID: 127438
    ShapeSuitID: 127441
    GradeResourceLen: tunianxianding
    KarNameLen: 六道魔尊
  - KartID: 10020
    ShapeSuitID: 126358
    KarNameLen: 新手赛车-黑爵
  - KartID: 81293
    ShapeSuitID: 126357
    KarNameLen: 黑域电魔-玄冥
  - KartID: 77236
    ShapeSuitID: 126356
    KarNameLen: 终极猛兽-幽冥骑士
  - KartID: 12720
    ShapeSuitID: 123506
    KarNameLen: 雷诺-车王盾铠
  - KartID: 86998
    ShapeSuitID: 123502
    KarNameLen: M18-祝融
  - KartID: 98263
    ShapeSuitID: 123501
    KarNameLen: 至尊-火鲤
  - KartID: 120646
    ShapeSuitID: 122200
    KarNameLen: 镇海之戟-敖丙
  - KartID: 90945
    ShapeSuitID: 122199
    KarNameLen: 众神之神-哪吒
  - KartID: 106673
    ShapeSuitID: 120657
    KarNameLen: 智慧之神-句芒
  - KartID: 98830
    ShapeSuitID: 119066
    KarNameLen: 爆天雷诺-冰蓝
  - KartID: 98830
    ShapeSuitID: 119065
    KarNameLen: 119065
  - KartID: 98830
    ShapeSuitID: 119064
    KarNameLen: 爆天雷诺-黑金
  - KartID: 119059
    ShapeSuitID: 119063
    KarNameLen: 119063
  - KartID: 75808
    ShapeSuitID: 119062
    GradeResourceLen: wuhushangjiang
    KarNameLen: 针尖王者-马超
  - KartID: 90945
    ShapeSuitID: 117941
    KarNameLen: 众神之神-星云
  - KartID: 70047
    ShapeSuitID: 117934
    GradeResourceLen: wuhushangjiang
    KarNameLen: 麦凯伦-赵云
  - KartID: 17661
    ShapeSuitID: 116740
    KarNameLen: 黑夜传说-曜影
  - KartID: 74362
    ShapeSuitID: 116735
    GradeResourceLen: wuhushangjiang
    KarNameLen: 爆天甲-黄忠
  - KartID: 81293
    ShapeSuitID: 115159
    GradeResourceLen: wuhushangjiang
    KarNameLen: 黑域电魔-张飞
  - KartID: 106673
    ShapeSuitID: 113415
    KarNameLen: 智慧之神Kitty限定
  - KartID: 112183
    ShapeSuitID: 113414
    KarNameLen: 射手座-艾俄罗斯
  - KartID: 13703
    ShapeSuitID: 113413
    GradeResourceLen: wuhushangjiang
    KarNameLen: S青龙偃月刀-关羽
  - KartID: 95683
    ShapeSuitID: 112178
    KarNameLen: 暗黑波塞冬
  - KartID: 90945
    ShapeSuitID: 110711
    KarNameLen: 众神之神-麒麟
  - KartID: 74362
    ShapeSuitID: 110709
    KarNameLen: 爆天甲-朋克
  - KartID: 126352
    ShapeSuitID: 124686
    KarNameLen: 冰魂-樱寒