- ID: 402
  Name: 跳跳模式
  Head: 0
  End: 0
  Loop: true
  Round: 1
- ID: 600
  Name: 奇迹之城
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 601
  Name: 极速冲刺
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 602
  Name: 情定巴黎
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 606
  Name: 极速长城
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 619
  Name: 极速核电站轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 620
  Name: 樱花富士山轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 1

- ID: 621
  Name: 极地冰镇轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 622
  Name: 浪漫冬日
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 623
  Name: 龙门新春轮滑
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 624
  Name: 法老领地
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 625
  Name: 天堂之城轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 626
  Name: 海湾军港
  Head: 0
  End: 0
  Loop: true
  Round: 1
- ID: 627
  Name: 风车牧场轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 628
  Name: 城市网吧轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 629
  Name: 原野山丘
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 630
  Name: 枫林物语
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 631
  Name: 国境之南轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 632
  Name: 薰衣草庄园轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 633
  Name: 精灵之森轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 634
  Name: 萌怪星球轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 635
  Name: 维京海港轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 636
  Name: 王国之路轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 637
  Name: 春风唐韵轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 638
  Name: 我们恋爱吧轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 639
  Name: happy！大眼萌轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 640
  Name: 糖果密境轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 641
  Name: 云端小镇轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 652
  Name: 疯狂玩具城
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 653
  Name: 舒马赫赛车场轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 654
  Name: 侏罗纪公园轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 655
  Name: 兔兔复活岛轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 656
  Name: 阳光码头轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 657
  Name: 香波岛轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 658
  Name: 洛杉矶轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 659
  Name: 情迷爱琴海轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 660
  Name: 魔龙猎场轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 661
  Name: 梦幻珊瑚海轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 662
  Name: 樱花祭轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 663
  Name: VANS机场轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 664
  Name: 广寒仙境轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 665
  Name: 小猪部落轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 666
  Name: 圣诞奇缘轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 667
  Name: 天空树轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 668
  Name: 萌犬贺春轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 669
  Name: 星星火车站轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 670
  Name: 南国海岛轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 671
  Name: 晶焰矿山轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 672
  Name: 恶龙城轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 673
  Name: 西湖轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 674
  Name: 卡帕多西亚轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 675
  Name: 西部荒野轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 676
  Name: 阿拉丁轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 677
  Name: 梦回波斯湾轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 1
- ID: 678
  Name: 繁华巴比伦轮滑版
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 607
  Name: 回音山谷
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 608
  Name: 地中海初夏
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 609
  Name: 飞过云端
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 610
  Name: 世界杯狂想曲
  Head: 0
  End: 0
  Loop: true
  Round: 1
- ID: 611
  Name: 烟花六月
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 612
  Name: 起风了
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 613
  Name: 雪地冲刺
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 614
  Name: 樱兰高校
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 615
  Name: 波斯古迹
  Head: 0
  End: 0
  Loop: false
  Round: 1
- ID: 616
  Name: 都市魅影
  Head: 0
  End: 0
  Loop: true
  Round: 2

- ID: 617
  Name: 仙林幻境
  Head: 0
  End: 0
  Loop: true
  Round: 2
- ID: 618
  Name: 冰封之城
  Head: 0
  End: 0
  Loop: true
  Round: 2