- Level: 5
  JumpLevel: 1
  BoxFlag: 5
  Checkpoint: [28]
  IsDragonGate: 5
- Level: 10
  JumpLevel: 2
  BoxFlag: 10
  Checkpoint: [67]
  IsDragonGate: 10
- Level: 15
  JumpLevel: 2
  BoxFlag: 15
  Checkpoint: [106]
  IsDragonGate: 15
- Level: 20
  JumpLevel: 2
  BoxFlag: 20
  Checkpoint: [149]
  IsDragonGate: 20
- Level: 25
  JumpLevel: 3
  BoxFlag: 25
  Checkpoint: [177]
  IsDragonGate: 25
- Level: 30
  JumpLevel: 4
  BoxFlag: 30
  Checkpoint: [218]
  IsDragonGate: 30
- Level: 35
  JumpLevel: 2
  BoxFlag: 35
  Checkpoint: [257]
  IsDragonGate: 35
- Level: 40
  JumpLevel: 3
  BoxFlag: 40
  Checkpoint: [291]
  IsDragonGate: 40
- Level: 45
  JumpLevel: 3
  BoxFlag: 45
  Checkpoint: [328]
  IsDragonGate: 45
- Level: 50
  JumpLevel: 3
  BoxFlag: 50
  Checkpoint: [362]
  IsDragonGate: 50
- Level: 55
  JumpLevel: 5
  BoxFlag: 55
  Checkpoint: [395]
  IsDragonGate: 55
- Level: 60
  JumpLevel: 3
  BoxFlag: 60
  Checkpoint: [423]
  IsDragonGate: 60
- Level: 65
  JumpLevel: 3
  BoxFlag: 65
  Checkpoint: [459]
  IsDragonGate: 65
- Level: 70
  JumpLevel: 4
  BoxFlag: 70
  Checkpoint: [492]
  IsDragonGate: 70
- Level: 75
  JumpLevel: 5
  BoxFlag: 75
  Checkpoint: [521]
  IsDragonGate: 75
- Level: 80
  JumpLevel: 5
  BoxFlag: 80
  Checkpoint: [551]
  IsDragonGate: 80
- Level: 85
  JumpLevel: 3
  BoxFlag: 85
  Checkpoint: [588]
  IsDragonGate: 85
- Level: 90
  JumpLevel: 2
  BoxFlag: 90
  Checkpoint: [616]
  IsDragonGate: 90
- Level: 95
  JumpLevel: 5
  BoxFlag: 95
  Checkpoint: [666]
  IsDragonGate: 95
- Level: 100
  JumpLevel: 0
  BoxFlag: 100
  Checkpoint: [723]
  IsDragonGate: 100
- Level: 1
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [3]
  IsDragonGate: 0
- Level: 2
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [7]
  IsDragonGate: 0
- Level: 3
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [13]
  IsDragonGate: 0
- Level: 4
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [24]
  IsDragonGate: 0
- Level: 6
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [37]
  IsDragonGate: 0
- Level: 7
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [44]
  IsDragonGate: 0
- Level: 8
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [50]
  IsDragonGate: 0
- Level: 9
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [59]
  IsDragonGate: 0
- Level: 11
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [72]
  IsDragonGate: 0
- Level: 12
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [79]
  IsDragonGate: 0
- Level: 13
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [93]
  IsDragonGate: 0
- Level: 14
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [99]
  IsDragonGate: 0
- Level: 16
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [114]
  IsDragonGate: 0
- Level: 17
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [119]
  IsDragonGate: 0
- Level: 18
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [132]
  IsDragonGate: 0
- Level: 19
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [139]
  IsDragonGate: 0
- Level: 21
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [157]
  IsDragonGate: 0
- Level: 22
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [164]
  IsDragonGate: 0
- Level: 23
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [169]
  IsDragonGate: 0
- Level: 24
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [174]
  IsDragonGate: 0
- Level: 26
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [186]
  IsDragonGate: 0
- Level: 27
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [195]
  IsDragonGate: 0
- Level: 28
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [201]
  IsDragonGate: 0
- Level: 29
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [212]
  IsDragonGate: 0
- Level: 31
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [223]
  IsDragonGate: 0
- Level: 32
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [230]
  IsDragonGate: 0
- Level: 33
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [245]
  IsDragonGate: 0
- Level: 34
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [250]
  IsDragonGate: 0
- Level: 36
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [266]
  IsDragonGate: 0
- Level: 37
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [271]
  IsDragonGate: 0
- Level: 38
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [277]
  IsDragonGate: 0
- Level: 39
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [284]
  IsDragonGate: 0
- Level: 41
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [301]
  IsDragonGate: 0
- Level: 42
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [310]
  IsDragonGate: 0
- Level: 43
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [315]
  IsDragonGate: 0
- Level: 44
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [320]
  IsDragonGate: 0
- Level: 46
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [333]
  IsDragonGate: 0
- Level: 47
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [339]
  IsDragonGate: 0
- Level: 48
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [349]
  IsDragonGate: 0
- Level: 49
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [356]
  IsDragonGate: 0
- Level: 51
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [365]
  IsDragonGate: 0
- Level: 52
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [374]
  IsDragonGate: 0
- Level: 53
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [379]
  IsDragonGate: 0
- Level: 54
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [383]
  IsDragonGate: 0
- Level: 56
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [399]
  IsDragonGate: 0
- Level: 57
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [407]
  IsDragonGate: 0
- Level: 58
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [412]
  IsDragonGate: 0
- Level: 59
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [417]
  IsDragonGate: 0
- Level: 61
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [427]
  IsDragonGate: 0
- Level: 62
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [435]
  IsDragonGate: 0
- Level: 63
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [441]
  IsDragonGate: 0
- Level: 64
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [447]
  IsDragonGate: 0
- Level: 66
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [467]
  IsDragonGate: 0
- Level: 67
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [476]
  IsDragonGate: 0
- Level: 68
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [481]
  IsDragonGate: 0
- Level: 69
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [485]
  IsDragonGate: 0
- Level: 71
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [500]
  IsDragonGate: 0
- Level: 72
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [505]
  IsDragonGate: 0
- Level: 73
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [510]
  IsDragonGate: 0
- Level: 74
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [516]
  IsDragonGate: 0
- Level: 76
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [529]
  IsDragonGate: 0
- Level: 77
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [533]
  IsDragonGate: 0
- Level: 78
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [540]
  IsDragonGate: 0
- Level: 79
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [546]
  IsDragonGate: 0
- Level: 81
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [557]
  IsDragonGate: 0
- Level: 82
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [569]
  IsDragonGate: 0
- Level: 83
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [574]
  IsDragonGate: 0
- Level: 84
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [582]
  IsDragonGate: 0
- Level: 86
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [593]
  IsDragonGate: 0
- Level: 87
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [598]
  IsDragonGate: 0
- Level: 88
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [603]
  IsDragonGate: 0
- Level: 89
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [607]
  IsDragonGate: 0
- Level: 91
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [621]
  IsDragonGate: 0
- Level: 92
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [631]
  IsDragonGate: 0
- Level: 93
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [642]
  IsDragonGate: 0
- Level: 94
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [653]
  IsDragonGate: 0
- Level: 96
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [679]
  IsDragonGate: 0
- Level: 97
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [688]
  IsDragonGate: 0
- Level: 98
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [707]
  IsDragonGate: 0
- Level: 99
  JumpLevel: 0
  BoxFlag: 0
  Checkpoint: [718]
  IsDragonGate: 0
