- BuffId: 113
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "极速提升"
  BuffDes: "每3次使用氮气，5秒内平跑极速能力+6"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 116
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "动力提升"
  BuffDes: "每次进入漂移，40%概率5秒内氮气动力+9"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 121
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气增强"
  BuffDes: "每6秒，40%概率5秒内氮气极速能力+4"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 124
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "小喷强化"
  BuffDes: "每8次使用小喷，4秒内小喷极速能力+8"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 127
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "小喷动力"
  BuffDes: "每次使用氮气，25%概率5秒内小喷动力+10"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 130
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "碰撞小喷"
  BuffDes: "撞墙或撞车后，立刻获得小喷且3秒内小喷动力+8（CD2秒）"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 133
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "腾空极速"
  BuffDes: "每次进入腾空，15%概率8秒内平跑极速能力+10"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 136
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "空落喷加强"
  BuffDes: "空喷落地喷时长+0.15秒，空喷落地喷最高速度+3"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 139
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "空喷强化"
  BuffDes: "每4次使用空喷，立刻获得小喷且3秒内小喷极速能力+4"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 142
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "起步加速"
  BuffDes: "起步15秒内小喷极速能力+6"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 145
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "集气增强"
  BuffDes: "每次进入漂移，立刻获得2%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 148
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "撞墙集气"
  BuffDes: "每次撞墙，30%概率获得33%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 151
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气强化"
  BuffDes: "获得氮气后，20%的概率氮气最高速度+2km/h，持续4秒"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 155
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "自动集气"
  BuffDes: "每秒自动集气1%"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 158
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "起步额外氮气"
  BuffDes: "起步立刻获得一个氮气，且8秒内氮气最高速度+2km/h，氮气动力+4"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 161
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "起步集气"
  BuffDes: "起步后8秒内，每秒自动集气2%"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 164
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气补偿"
  BuffDes: "每次使用氮气，10%概率立刻获得15%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 188
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "疾速鲤鱼"
  BuffDes: "化鲤技能结束后，8秒内获得额外速度+10"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 191
  Prob: 50
  BuffType: 0
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "超速集气"
  BuffDes: "使用化鲤技能时，每秒集气进度自动增长10%，持续8秒"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 178
  Prob: 50
  BuffType: 1
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 89941
  DailyExpKartTimeLimit: -1
  BuffName: "猎影"
  BuffDes: "装备后可以体验B级赛车――猎影。"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 179
  Prob: 50
  BuffType: 1
  BuffLev: 1
  ReduceDiscount: 10
  KartId: 82255
  DailyExpKartTimeLimit: -1
  BuffName: "狙击警探"
  BuffDes: "装备后可以体验B级赛车――狙击警探。"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 112
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "极速提升"
  BuffDes: "每3次使用氮气，6秒内平跑极速能力+8"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 115
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "动力提升"
  BuffDes: "每次进入漂移，50%概率7秒内氮气动力+10"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 120
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气增强"
  BuffDes: "每6秒，50%概率6秒内氮气极速能力+6"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 123
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "小喷强化"
  BuffDes: "每5次使用小喷，4秒内小喷极速能力+10"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 126
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "小喷动力"
  BuffDes: "每次使用氮气，30%概率5秒内小喷动力+18"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 129
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "碰撞小喷"
  BuffDes: "撞墙或撞车后，立刻获得小喷且3秒内小喷动力+18（CD2秒）"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 132
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "腾空极速"
  BuffDes: "每次进入腾空，30%概率8秒内平跑极速能力+10"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 135
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "空落喷加强"
  BuffDes: "空喷落地喷时长+0.15秒，空喷落地喷最高速度+7"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 138
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "空喷强化"
  BuffDes: "每3次使用空喷，立刻获得小喷且3秒内小喷极速能力+6"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 141
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "起步加速"
  BuffDes: "起步20秒内小喷极速能力+9"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 144
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "集气增强"
  BuffDes: "每次进入漂移，立刻获得4%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 147
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "撞墙集气"
  BuffDes: "每次撞墙，50%概率获得40%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 150
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气强化"
  BuffDes: "获得氮气后，25%的概率氮气最高速度+2.5km/h，持续6秒"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 154
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "自动集气"
  BuffDes: "每秒自动集气1.5%"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 157
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "起步额外氮气"
  BuffDes: "起步立刻获得一个氮气，且10秒内氮气最高速度+2.5km/h，氮气动力+5"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 160
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "起步集气"
  BuffDes: "起步后10秒内，每秒自动集气3%"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 163
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气补偿"
  BuffDes: "每次使用氮气，13%概率立刻获得23%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 187
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "疾速鲤鱼"
  BuffDes: "化鲤技能结束后，8秒内获得额外速度+20"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 190
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "超速集气"
  BuffDes: "使用化鲤技能时，每秒集气进度自动增长15%，持续8秒"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 118
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "wcw极速"
  BuffDes: "使用氮气即可达到wcw速度"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 176
  Prob: 50
  BuffType: 1
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 72278
  DailyExpKartTimeLimit: 8
  BuffName: "血月"
  BuffDes: "装备后可以体验A级赛车――血月。"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 177
  Prob: 50
  BuffType: 1
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 76200
  DailyExpKartTimeLimit: 8
  BuffName: "魔甲战神"
  BuffDes: "装备后可以体验A级赛车――魔甲战神。"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 182
  Prob: 50
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "鲤鱼时刻"
  BuffDes: "每次使用化鲤技能时，50%概率闯关时间额外+1.5秒（每棒上限2次）"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 185
  Prob: 0
  BuffType: 0
  BuffLev: 2
  ReduceDiscount: 15
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "强力应援"
  BuffDes: "为队友完美打call，3秒队友获得平跑+5，可重复触发"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 111
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "极速提升"
  BuffDes: "每3次使用氮气，8秒内平跑极速能力+12"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 114
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "动力提升"
  BuffDes: "每次进入漂移，60%概率8秒内氮气动力+15"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 119
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气增强"
  BuffDes: "每6秒，70%概率6秒内氮气极速能力+9"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 122
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "小喷强化"
  BuffDes: "每5次使用小喷，5秒内小喷极速能力+15"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 125
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "小喷动力"
  BuffDes: "每次使用氮气，60%概率5秒内小喷动力+18"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 128
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "碰撞小喷"
  BuffDes: "撞墙或撞车后，立刻获得小喷且5秒内小喷动力+25（CD2秒）"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 131
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "腾空极速"
  BuffDes: "每次进入腾空，60%概率8秒内平跑极速能力+10"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 134
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "空落喷加强"
  BuffDes: "空喷落地喷时长+0.4秒，空喷落地喷最高速度+10"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 137
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "空喷强化"
  BuffDes: "每2次使用空喷，立刻获得小喷且3秒内小喷极速能力+8"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 140
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "起步加速"
  BuffDes: "起步30秒内小喷极速能力+12"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 143
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "集气增强"
  BuffDes: "每次进入漂移，立刻获得8%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 146
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "撞墙集气"
  BuffDes: "每次撞墙，60%概率获得70%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 149
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气强化"
  BuffDes: "获得氮气后，40%的概率氮气最高速度+3km/h，持续6秒"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 153
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "自动集气"
  BuffDes: "每3秒获得8%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 156
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "起步额外氮气"
  BuffDes: "起步立刻获得一个氮气，且20秒内氮气最高速度+3km/h，氮气动力+5"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 159
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "起步集气"
  BuffDes: "起步后20秒内，每秒自动集气3%"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 162
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气补偿"
  BuffDes: "每次使用氮气，25%概率立刻获得23%集气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 186
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "疾速鲤鱼"
  BuffDes: "化鲤技能结束后，8秒内获得额外速度+30"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 189
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "超速集气"
  BuffDes: "使用化鲤技能时，每秒集气进度自动增长20%，持续8秒"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 152
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "额外氮气"
  BuffDes: "开局使用第一个氮气时，额外获得一个氮气"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 101
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "加速推进"
  BuffDes: "飞机冲关时，闯关时间+1秒（每棒上限2次）"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 103
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "打call加成"
  BuffDes: "为队友打call，100%闯关时间额外+1秒"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 105
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "超级加速"
  BuffDes: "进入加速带时，100%闯关时间+1秒（每棒上限2次）"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 107
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "助力起跑"
  BuffDes: "每棒起跑时，100%闯关时间+1秒"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 109
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "喷射加成"
  BuffDes: "使用双喷（含cww、wcw）后，闯关时间+1秒（每棒上限2次）"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 117
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "cww极速"
  BuffDes: "使用氮气即可达到cww最高速度"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 174
  Prob: 50
  BuffType: 1
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 63431
  DailyExpKartTimeLimit: 5
  BuffName: "赤道极光"
  BuffDes: "装备后可以体验S级赛车――赤道极光。"
  Icon: 0
  BuffShape: 1
  IsCanLevUp: 0
- BuffId: 175
  Prob: 50
  BuffType: 1
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 34851
  DailyExpKartTimeLimit: 5
  BuffName: "闪电风暴"
  BuffDes: "装备后可以体验S级赛车――闪电风暴。"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 180
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气补给"
  BuffDes: "使用化鲤技能冲关时，立即获得两个氮气"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 181
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "鲤鱼时刻"
  BuffDes: "每次使用化鲤技能时，100%概率闯关时间额外+1.5秒（每棒上限2次）"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 183
  Prob: 50
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "氮气充能"
  BuffDes: "使用化鲤技能时，立刻获得一个氮气"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
- BuffId: 184
  Prob: 0
  BuffType: 0
  BuffLev: 3
  ReduceDiscount: 20
  KartId: 0
  DailyExpKartTimeLimit: 0
  BuffName: "强力应援"
  BuffDes: "为队友完美打call，3秒队友获得平跑+10，可重复触发"
  Icon: 0
  BuffShape: 2
  IsCanLevUp: 0
