- ID: 4
  Name: "魅力红人"
  ValueDesc: "历史累积魅力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 1
  Name: "等级红人"
  ValueDesc: "当前经验值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 3
  Name: "荣誉红人"
  ValueDesc: "当前荣誉值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 177
  Name: "赛车展览馆珍藏度"
  ValueDesc: "当前珍藏度值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 174
  Name: "排位赛主题赛道排行"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: true
- ID: 173
  Name: "排位赛主题赛道排行"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: true
- ID: 172
  Name: "排位赛主题赛道排行"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: true
- ID: 171
  Name: "排位赛主题赛道排行"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: true
- ID: 170
  Name: "排位赛主题赛道排行"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: true
- ID: 143
  Name: "赛道DIY关卡10地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 142
  Name: "赛道DIY关卡9地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 141
  Name: "赛道DIY关卡8地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 140
  Name: "赛道DIY关卡7地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 139
  Name: "赛道DIY关卡6地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 138
  Name: "赛道DIY关卡5地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 137
  Name: "赛道DIY关卡4地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 136
  Name: "赛道DIY关卡3地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 135
  Name: "赛道DIY关卡2地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 134
  Name: "赛道DIY关卡1地图"
  ValueDesc: "单局时间"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 131
  Name: "酷比大作战周积分"
  ValueDesc: "周累积酷比大作战"
  TitleName: ""
  IsEnableSelfRank: true
- ID: 175
  Name: "飞车主题屋珍藏度"
  ValueDesc: "珍藏度"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 130
  Name: "排位赛车神榜"
  ValueDesc: "排位赛积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 109
  Name: "珍宝红人"
  ValueDesc: "珍藏度2"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 108
  Name: "多宠天梯积分"
  ValueDesc: "天梯积分"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "战队战斗力"
    IntParaDesc1: "被膜拜次数"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: true
- ID: 106
  Name: "飞车主题屋珍藏度"
  ValueDesc: "珍藏度"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 100
  Name: "宠物PK战斗力"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 179
  Name: "极限挑战3期组队"
  ValueDesc: "极限挑战3期组队"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "用时"
    IntParaDesc1: "是否星秀主播+直播"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 181
  Name: "极限挑战4期单人"
  ValueDesc: "极限挑战4期单人"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "用时"
    IntParaDesc1: "是否星秀主播+直播"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 178
  Name: "极限挑战3期单人"
  ValueDesc: "极限挑战3期单人"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "用时"
    IntParaDesc1: "是否星秀主播+直播"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 176
  Name: "极限挑战3期组队"
  ValueDesc: "极限挑战3期组队"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "用时"
    IntParaDesc1: "是否星秀主播+直播"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 123
  Name: "关卡挑战日最高积分"
  ValueDesc: "日积分"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "通关数"
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 118
  Name: "修罗夺金赛跨服周"
  ValueDesc: "修罗夺金赛跨服周"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "场次"
    IntParaDesc1: "是否星秀主播+直播"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 116
  Name: "修罗夺金赛跨服日"
  ValueDesc: "修罗夺金赛跨服日"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "场次"
    IntParaDesc1: "是否星秀主播+直播"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 113
  Name: "跨服幸运大奖赛赛"
  ValueDesc: "跨服幸运大奖赛赛"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 112
  Name: "跨服幸运大奖赛赛"
  ValueDesc: "跨服幸运大奖赛赛"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 111
  Name: "幸运大奖赛赛季积分"
  ValueDesc: "幸运大奖赛赛季积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 110
  Name: "幸运大奖赛赛季积分"
  ValueDesc: "幸运大奖赛赛季积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 166
  Name: "极限挑战2期单人"
  ValueDesc: "极限挑战2期单人"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "用时"
    IntParaDesc1: "是否星秀主播+直播"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 167
  Name: "极限挑战2期组队"
  ValueDesc: "极限挑战2期组队"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "用时"
    IntParaDesc1: "是否星秀主播+直播"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 182
  Name: "极限挑战4期组队"
  ValueDesc: "极限挑战4期组队"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "用时"
    IntParaDesc1: "是否星秀主播+直播"
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 168
  Name: "短途世界赛周胜点"
  ValueDesc: "周胜点"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 98
  Name: "奥运奖牌红人"
  ValueDesc: "历史奥运奖牌值"
  TitleName: ""
  IsEnableSelfRank: true
- ID: 99
  Name: "日奥运奖牌红人"
  ValueDesc: "当日奥运奖牌值"
  TitleName: ""
  IsEnableSelfRank: true
- ID: 125
  Name: "情侣二宝被点赞数"
  ValueDesc: ""
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "主帐号Uin"
    IntParaDesc1: "副帐号Uin"
    StrParaDesc0: "主帐号昵称"
    StrParaDesc1: "副帐号昵称"
  IsEnableSelfRank: false
- ID: 126
  Name: "情侣二宝红人"
  ValueDesc: ""
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "主帐号Uin"
    IntParaDesc1: "副帐号Uin"
    StrParaDesc0: "主帐号昵称"
    StrParaDesc1: "副帐号昵称"
  IsEnableSelfRank: false
- ID: 124
  Name: "情侣二宝每日心情"
  ValueDesc: ""
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "主帐号Uin"
    IntParaDesc1: "副帐号Uin"
    StrParaDesc0: "主帐号昵称"
    StrParaDesc1: "副帐号昵称"
  IsEnableSelfRank: false
- ID: 97
  Name: "情侣宝宝被点赞数"
  ValueDesc: ""
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "主帐号Uin"
    IntParaDesc1: "副帐号Uin"
    StrParaDesc0: "主帐号昵称"
    StrParaDesc1: "副帐号昵称"
  IsEnableSelfRank: false
- ID: 96
  Name: "情侣宝宝每日心情"
  ValueDesc: ""
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "主帐号Uin"
    IntParaDesc1: "副帐号Uin"
    StrParaDesc0: "主帐号昵称"
    StrParaDesc1: "副帐号昵称"
  IsEnableSelfRank: false
- ID: 90
  Name: "宝宝红人"
  ValueDesc: ""
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "主帐号Uin"
    IntParaDesc1: "副帐号Uin"
    StrParaDesc0: "主帐号昵称"
    StrParaDesc1: "副帐号昵称"
  IsEnableSelfRank: false
- ID: 88
  Name: "千层塔积分"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 91
  Name: "千层塔总积分"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 94
  Name: "拉力赛赛季荣誉"
  ValueDesc: ""
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: true
- ID: 95
  Name: "拉力赛总荣誉"
  ValueDesc: ""
  TitleName: ""
  OtherInfo:
    IntParaDesc0: ""
    IntParaDesc1: ""
    StrParaDesc0: ""
    StrParaDesc1: ""
  IsEnableSelfRank: true
- ID: 69
  Name: "星光红人"
  ValueDesc: "秀场财富值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 76
  Name: "赛季荣誉"
  ValueDesc: "车队本赛季获得荣"
  TitleName: "车队"
  OtherInfo:
    IntParaDesc0: "队长Uin"
    IntParaDesc1: ""
    StrParaDesc0: "队长昵称"
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 74
  Name: "赛季战勋"
  ValueDesc: "本赛季获得战勋"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "车队ID"
    IntParaDesc1: "空数据"
    StrParaDesc0: "车队"
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 37
  Name: "竞技红人"
  ValueDesc: "当前竞技点"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 38
  Name: "冠军红人"
  ValueDesc: "当前竞技冠军总数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 35
  Name: "成就红人"
  ValueDesc: "当前成就点"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 44
  Name: "回馈红人"
  ValueDesc: "历史回馈点"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 133
  Name: "十周年回馈大兑换"
  ValueDesc: "周年币总数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 132
  Name: "十周年回馈大兑换"
  ValueDesc: "周年币数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 144
  Name: "集福贺新春"
  ValueDesc: "福字数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 128
  Name: "欢乐扭蛋日榜"
  ValueDesc: "黄金币数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 145
  Name: "集福贺新春"
  ValueDesc: "福字总数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 107
  Name: "国庆五角星产出次"
  ValueDesc: "五角星数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 122
  Name: "八一勋章总榜"
  ValueDesc: "劳动勋章数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 121
  Name: "八一勋章日榜"
  ValueDesc: "劳动勋章数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 72
  Name: "火线红人"
  ValueDesc: "当前赛季警匪模式"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 155
  Name: "赛道寻宝"
  ValueDesc: "宝石数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 156
  Name: "赛道寻宝"
  ValueDesc: "宝石总数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 129
  Name: "欢乐扭蛋总榜"
  ValueDesc: "黄金币总数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 114
  Name: "五一寻宝劳动勋章"
  ValueDesc: "劳动勋章数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 66
  Name: "巡回淘汰赛"
  ValueDesc: "累计三冠王次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 81
  Name: "千层塔大区积分"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 82
  Name: "千层塔大区积分"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 83
  Name: "千层塔大区积分"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 84
  Name: "千层塔大区积分"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 85
  Name: "千层塔大区积分"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 86
  Name: "千层塔大区积分"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 87
  Name: "千层塔大区积分"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: false
- ID: 89
  Name: "车队PK赛赏金点"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: true
- ID: 92
  Name: "整蛊愚人乐赠送宝"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: true
- ID: 93
  Name: "整蛊愚人乐收到宝"
  ValueDesc: ""
  TitleName: ""
  IsEnableSelfRank: true
- ID: 75
  Name: "车队总荣誉"
  ValueDesc: "车队历史积累总荣"
  TitleName: "车队"
  OtherInfo:
    IntParaDesc0: "队长Uin"
    IntParaDesc1: ""
    StrParaDesc0: "队长昵称"
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 73
  Name: "战勋红人"
  ValueDesc: "历史积累战勋"
  TitleName: ""
  OtherInfo:
    IntParaDesc0: "车队ID"
    IntParaDesc1: "空数据"
    StrParaDesc0: "车队"
    StrParaDesc1: ""
  IsEnableSelfRank: false
- ID: 65
  Name: "进阶改装红人"
  ValueDesc: "累计进阶改装次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 57
  Name: "后花园红人"
  ValueDesc: "当前后花园成长值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 67
  Name: "消费寻宝达人"
  ValueDesc: "累计寻宝次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 68
  Name: "日消费寻宝达人"
  ValueDesc: "当日累计寻宝次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 71
  Name: "赛季警察积分"
  ValueDesc: "当前赛季警察积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 70
  Name: "赛季匪徒积分"
  ValueDesc: "当前赛季匪徒积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 58
  Name: "钻皇红人"
  ValueDesc: "当前钻皇成长值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 53
  Name: "情侣贵族红人"
  ValueDesc: "当前情侣贵族成长"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 43
  Name: "皇族红人"
  ValueDesc: "当前皇族成长值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 45
  Name: "贵族红人"
  ValueDesc: "当前车队贵族成长"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 56
  Name: "红包赠送红人"
  ValueDesc: "红包赠送红人"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 46
  Name: "人气红人"
  ValueDesc: "当前人气值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 55
  Name: "历史最高PVE积分"
  ValueDesc: "历史最高PVE积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 36
  Name: "宝石红人"
  ValueDesc: "宝石点数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 42
  Name: "恩爱红人"
  ValueDesc: "当前恩爱度"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 30
  Name: "情侣红人"
  ValueDesc: "当前亲密度"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 33
  Name: "名师红人"
  ValueDesc: "当前名师点"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 31
  Name: "舞蹈红人"
  ValueDesc: "当前舞力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 8
  Name: "改装红人"
  ValueDesc: "累积改装次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 34
  Name: "养鱼红人"
  ValueDesc: "当前经验值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 32
  Name: "鲜花红人"
  ValueDesc: "当前心动值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 2
  Name: "酷币红人"
  ValueDesc: "当前酷币数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 54
  Name: "日最高PVE积分"
  ValueDesc: "当日最高PVE积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 5
  Name: "日魅力红人"
  ValueDesc: "当日累积魅力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 48
  Name: "日赠送红人"
  ValueDesc: "日赠送钻石玫瑰数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 6
  Name: "周魅力红人"
  ValueDesc: "当周累积魅力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 60
  Name: "周人气红人"
  ValueDesc: "当周累积后花园总"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 64
  Name: "周穿梭达人"
  ValueDesc: "当周累积穿梭积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 79
  Name: "周嘉年华达人"
  ValueDesc: "当周累积嘉年华积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 7
  Name: "月魅力红人"
  ValueDesc: "当月累积魅力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 10
  Name: "日喇叭红人"
  ValueDesc: "当日喇叭使用数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 11
  Name: "周喇叭红人"
  ValueDesc: "当周喇叭使用数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 13
  Name: "日表白红人"
  ValueDesc: "日表白次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 14
  Name: "周表白红人"
  ValueDesc: "周表白次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 16
  Name: "日祝福红人"
  ValueDesc: "日祝福次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 17
  Name: "周祝福红人"
  ValueDesc: "周祝福次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 146
  Name: "世界巡回赛排行榜"
  ValueDesc: "积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 147
  Name: "世界巡回赛排行榜"
  ValueDesc: "积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 148
  Name: "世界巡回赛排行榜"
  ValueDesc: "积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 149
  Name: "世界巡回赛排行榜"
  ValueDesc: "积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 169
  Name: "玉兔逐月里程值"
  ValueDesc: "玩家累计获得里程"
  TitleName: ""
  IsEnableSelfRank: true
- ID: 150
  Name: "世界巡回赛排行榜"
  ValueDesc: "积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 151
  Name: "世界巡回赛排行榜"
  ValueDesc: "积分"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 152
  Name: "世界巡回赛排行榜"
  ValueDesc: "积分"
  TitleName: ""
  IsEnableSelfRank: false
