- ID: 4
  Name: "魅力红人"
  ValueDesc: "历史累积魅力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 1
  Name: "等级红人"
  ValueDesc: "当前经验值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 3
  Name: "荣誉红人"
  ValueDesc: "当前荣誉值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 37
  Name: "竞技红人"
  ValueDesc: "当前竞技点"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 38
  Name: "冠军红人"
  ValueDesc: "当前竞技冠军总数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 35
  Name: "成就红人"
  ValueDesc: "当前成就点"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 44
  Name: "回馈红人"
  ValueDesc: "历史回馈点"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 43
  Name: "皇族红人"
  ValueDesc: "当前皇族成长值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 45
  Name: "贵族红人"
  ValueDesc: "当前车队贵族成长"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 46
  Name: "人气红人"
  ValueDesc: "当前人气值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 36
  Name: "宝石红人"
  ValueDesc: "宝石点数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 42
  Name: "恩爱红人"
  ValueDesc: "当前恩爱度"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 30
  Name: "情侣红人"
  ValueDesc: "当前亲密度"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 33
  Name: "名师红人"
  ValueDesc: "当前名师点"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 31
  Name: "舞蹈红人"
  ValueDesc: "当前舞力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 8
  Name: "改装红人"
  ValueDesc: "累积改装次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 34
  Name: "养鱼红人"
  ValueDesc: "当前经验值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 32
  Name: "鲜花红人"
  ValueDesc: "当前心动值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 2
  Name: "酷币红人"
  ValueDesc: "当前酷币数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 5
  Name: "日魅力红人"
  ValueDesc: "当日累积魅力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 48
  Name: "日赠送红人"
  ValueDesc: "日赠送钻石玫瑰数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 6
  Name: "周魅力红人"
  ValueDesc: "当周累积魅力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 7
  Name: "月魅力红人"
  ValueDesc: "当月累积魅力值"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 10
  Name: "日喇叭红人"
  ValueDesc: "当日喇叭使用数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 11
  Name: "周喇叭红人"
  ValueDesc: "当周喇叭使用数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 13
  Name: "日表白红人"
  ValueDesc: "日表白次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 14
  Name: "周表白红人"
  ValueDesc: "周表白次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 16
  Name: "日祝福红人"
  ValueDesc: "日祝福次数"
  TitleName: ""
  IsEnableSelfRank: false
- ID: 17
  Name: "周祝福红人"
  ValueDesc: "周祝福次数"
  TitleName: ""
  IsEnableSelfRank: false
